export type TrafficDisruption = {
    id: number,
    disruption_id: string,
    status: string,
    closure: string,
    on_street: string,
    impact: string,
    start_date: string,
    finish_date: string,
    progress: number,
    details: string,
    description: string,
    activity_type: string,
    traffic_district: string,
    infrastructure: string,
    coordinate: [lon: number, lat: number],
};
